theme: jekyll-theme-merlot
show_downloads: true
google_analytics: UA-134924634-2
releasename: 2.1.20.0
releasetag: 2.1.20.0
releasebuild: 2.1.20.1172
exclude:
 - "bin"
 - "obj"
 - "*.exe"
 - "*.csproj"
 - "*.cs"
