theme: jekyll-theme-merlot
show_downloads: true
google_analytics: UA-134924634-2
releasename: 2.2.9.1
releasetag: 2.2.9.1701
releasebuild: 2.2.9.1701
exclude:
 - "bin"
 - "obj"
 - "*.exe"
 - "*.csproj"
 - "*.cs"
