theme: jekyll-theme-merlot
show_downloads: true
google_analytics: UA-134924634-2
releasename: 2.1.22.1
releasetag: 2.1.22.1267
releasebuild: 2.1.22.1267
exclude:
 - "bin"
 - "obj"
 - "*.exe"
 - "*.csproj"
 - "*.cs"
